version: "3.8"

services:
  web:
    container_name: pizza-web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - db
    command: ./docker-entrypoint.sh prod
    restart: unless-stopped
  db:
    image: mysql:latest
    container_name: pizza-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pizza-app:/data/db
    restart: unless-stopped

volumes:
  pizza-app:
