version: "3.8"

services:
  web:
    container_name: pizza-web
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes: 
      - .:/app
    command: ./docker-entrypoint.sh dev
  db:
    image: mysql:latest
    container_name: pizza-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pizza-app:/data/db

volumes:
  pizza-app:
