version: "3.8"

services:
  web:
    container_name: pizza-web
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes: 
      - .:/app
    command: ./docker-entrypoint.sh
  db:
    image: mysql:latest
    container_name: pizza-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'pizza-app'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    volumes:
      - pizza-app:/data/db

volumes:
  pizza-app:
