version: "3.8"

services:
  web:
    container_name: pizza-app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
  db:
    image: mysql:latest
    container_name: pizza-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'pizza-ordering'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    volumes:
      - pizza-ordering:/data/db

volumes:
  pizza-ordering:
